#!/bin/sh
cd "$(dirname "$0")"
rm -rf lib/
rm -rf index.d.ts
mkdir lib
yarn
gulp stylesProduction
tsc ./src/ts/components/ui/custom-scroll.tsx -d --jsx react --target ES5 --outDir ./lib
cp ./lib/custom-scroll.d.ts ./
mv custom-scroll.d.ts index.d.ts